[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "learnbuild123"
version = "0.0.1"
requires-python = ">=3.11"

dependencies = ["build123d", "notebook"]

[tool.setuptools]
py-modules = []
