# -*- coding: utf-8 -*-
"""Ipyvolume.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b3YzBKpdwsxQR-LUs2abNqm0LE14cX-w
"""

# prompt: Install ipyvolume in google colab

!pip install ipyvolume numpy-stl numpy
!jupyter nbextension enable --py --sys-prefix ipyvolume

import ipyvolume as ipv
from stl import mesh
import numpy as np

#!wget https://raw.githubusercontent.com/Buildbee/example-stl/main/ascii-cube.stl


my_mesh = mesh.Mesh.from_file('ascii-cube.stl')



fig = ipv.figure()
n = len(my_mesh.v0)
ipv.plot_trisurf(x=my_mesh.x.ravel(order='F'),
                 y=my_mesh.y.ravel(order='F'),
                 z=my_mesh.z.ravel(order='F'),
                 triangles=np.arange(3*n).reshape(n,3,order='F'),
                 color="orange")
ipv.show()